### ISSUE TITLE
Arc++ in the path

### ISSUE THREAD

**Issue by Aksej** [kimtg/Arcpp#1]
I tried to put arc++ into my path by symlinking `~/.local/bin/arc++` to the compiled binary in the cloned repository. This doesn't work – it seems `library.arc` doesn't get loaded that way. Linking `libary.arc` from `~/.local/bin/library.arc` didn't help. The readme doesn't contain information about how the binary decides where `library.arc` is.

**Comment by kimtg** [comment]
Try putting `library.arc` to the same directory as symlinked binary. (i.e. `~/.local/bin/arc++`)

**Comment by Aksej** [comment]
Unfortunately that doesn't work:

```
thomas@laptop:~/.local/bin$ ls
arc  arc++  bin  dat  docs  easy_install  f2py3  library.arc  Nomyx  poslin  poslin0  poslin1  poslin2  poslin-dyn  remwm  settings  shen  untabify  untabify-tree  wordlist  worldengine
thomas@laptop:~/.local/bin$ ./arc
Arc++ 0.10.8
> (= a 3)
3
> a
3
> 
thomas@laptop:~/.local/bin$ cd ~
thomas@laptop:~$ arc
Arc++ 0.10.8
> (= a 3)
Symbol not bound : =
> 
thomas@laptop:~$ whereis arc
arc: /home/thomas/.local/bin/arc
thomas@laptop:~$ 
```

Copying `library.arc` instead of symlinking it doesn't make a difference.

**Comment by kimtg** [comment]
library file is embedded now. No `library.arc` file.
